spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    driver-class-name: oracle.jdbc.OracleDriver
#		url: ${SPRING_DATASOURCE_URL}
#		username: ${SPRING_DATASOURCE_USERNAME}
#		password: ${SPRING_DATASOURCE_PASSWORD} 
#    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    show-sql: true
  

server:
  port: 8089

management:
  endpoints:
    web:
        base-path: /sesiones  
        path-mapping:
          health: health	